version: "3.8"

services:
  app:
    container_name: e_comm
    build:
      context: .
      dockerfile: deploy.dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/app
    env_file:
      - .env
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
