apiVersion: v1
kind: Secret
metadata:
  name: ecomm-secret
type: Opaque
data:
  DB_NAME: bGliZXJ0eQ==
  DB_HOST: ZXAtbGl0dGxlLXdhdGVyZmFsbC1hNWU0b2x3ay51cy1lYXN0LTIuYXdzLm5lb24udGVjaA==
  DB_USER: dWJlcmRiX293bmVy
  DB_PORT: NTQzMg==
  DB_PASSWD: eWRId05GQTkxcGJy
